---
# tasks file for apache
- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - include assert.yml"
  include_tasks: assert.yml

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - install apache httpd"
  package:
    name: "{{ httpd_packages }}"
    state: present

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - modify selinux settings"
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"
  loop: "{{ httpd_sebooleans }}"

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - allow connections to custom port"
  seport:
    ports: "{{ item }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"
  loop:
    - "{{ httpd_port }}"
    - "{{ httpd_ssl_port }}"

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - configure ssl"
  template:
    src: ssl.conf.j2
    dest: "{{ httpd_config_directory }}/ssl.conf"
  notify:
    - test httpd configuration validity
    - restart httpd

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - configure locations"
  template:
    src: location.conf.j2
    dest: "{{ httpd_config_directory }}/{{ item.name }}.conf"
  loop: "{{ httpd_locations }}"
  notify:
    - test httpd configuration validity
    - restart httpd
  when:
    - httpd_locations is defined
  loop_control:
    label: "{{ item.name }}"

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - configure vhosts"
  template:
    src: vhost.conf.j2
    dest: "{{ httpd_config_directory }}/{{ item.name }}.conf"
  loop: "{{ httpd_vhosts }}"
  notify:
    - test httpd configuration validity
    - restart httpd
  when:
    - httpd_vhosts is defined
  loop_control:
    label: "{{ item.name }}"

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - configure apache httpd"
  template:
    src: "{{ httpd_config_src }}"
    dest: "{{ httpd_config_dest }}"
  notify:
    - test httpd configuration validity
    - restart httpd

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - configure listening ports"
  template:
    src: "{{ httpd_ports_conf }}.j2"
    dest: "{{ httpd_server_root }}/{{ httpd_ports_conf }}"
  notify:
    - test httpd configuration validity
    - restart httpd
  when:
    - ansible_os_family == "Debian" or
      ansible_os_family == "Suse"

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - configure redirect from http to https"
  template:
    src: default_vhost.conf.j2
    dest: "{{ httpd_config_directory }}/default_vhost.conf"
  notify:
    - test httpd configuration validity
    - restart httpd

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - create docroot"
  file:
    path: "{{ item.documentroot }}"
    state: directory
  loop: "{{ httpd_vhosts }}"
  when:
    - httpd_vhosts is defined
    - item.documentroot is defined

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - start and enable httpd"
  service:
    name: "{{ httpd_service }}"
    state: started
    enabled: yes